<<<<<<< HEAD
[build-system]
requires = ["hatchling"]
build-backend= "hatchling.build"

[project]
name = "shape"
version = "0.1"
=======
[build-system]
requires = ["hatchling"]
build-backend= "hatchling.build"

[project]
name = "polynomials"
version = "0.1"
>>>>>>> f2f618b (Basic Polynomial Implementation)
